### ISSUE TITLE
newbiew feedback

### ISSUE THREAD

**Issue by razshare** [MircoT/py-pdp8-tk#2]
Salve!
Sono uno studente del primo anno di Informatica (Perugia).
Intanto la ringrazio per le lezioni extra e le esercitazioni di Architettura in parallelo a quelle del Professor Navarra.

Issue: Esame a breve - 0 esperienza in Python, come eseguo/compilo il progetto per provare il mio codice .asm?
PS: Ho Python 3.4.3 sulla macchina ( sorgente: https://www.python.org/downloads/ ) ed il progetto in Python dal suo Git.
![image](https://cloud.githubusercontent.com/assets/6891346/8672977/4cb7ccfe-2a33-11e5-977f-4272eb512986.png)

**Comment by MircoT** [comment]
Attualmente il progetto non è compatibile con Python 3, quindi per prima cosa installa **Python 2**. Una volta fatto questo basta cliccare due volte su ___main__.py_ per eseguire il programma e aprire i vari file **.asm**.

Chiudo l'_issue_ visto che non riguarda il programma.
